### ISSUE TITLE
self.$(this) doesn't work

### ISSUE THREAD

**Issue by atnartur** [matreshkajs/matreshka#23]
Здравствуйте. В матрешке версии 1.0.6 код ```self.$(this)``` работал. Сейчас (версия 1.2.0) это не работает. Исправляется просто конечно: надо просто убрать ```self```. Но все-таки интересно: баг это или фича?)

```javascript
this.bindNode('name', ':sandbox .name', {
    setValue: function(
        self.$(this).val(v);
    }
});
```

**Comment by finom** [comment]
@atnartur ``this`` в ``on``, ``getValue``, ``setValue`` и ``initialize`` - это сам элемент, а не объект, запустивший ``bindNode``. Т. е., если jQuery - определен глобально, можно писать так:
```js
 $(this).val(v);
```
Если используются модули (jQuery - не глобальная переменная), в функции Matreshka (MK) есть ссылка на текущую библиотеку:
```js
MK.$(this).val(v);
```
