### ISSUE TITLE
Multipage REST examples

### ISSUE THREAD

**Issue by kethomassen** [matreshkajs/matreshka#25]
It would be helpful to have a multipage (using director routing) example using REST to provide a more complete example that frameworks such as Ember, Backbone provide.

For example, an admin dashboard with multiple tables of stuff.

**Comment by finom** [comment]
Hi @kethomassen 

This is big work but I've got it.  Can you provide me links to applications you've meant?

Closing this issue since this is not framework issue. You still can comment it.

**Comment by finom** [comment]
@kethomassen thank you.
