### ISSUE TITLE
Cannot create property which contains dot

### ISSUE THREAD

**Issue by undermuz** [matreshkajs/matreshka#26]
http://jsfiddle.net/8d5o157b/

```javascript
var app = new Matreshka;
app.bindNode( 'int.int', '.int' );
console.log(Matreshka.version)
app.mediate('int.int', Number);

app.on('change:int.int', function(){
	console.log( app['int.int'] );
});
```

Раньше поддерживалась.

**Comment by finom** [comment]
@undermuz точка, собачка, звездочка (``. @ *``) это зарезервированные символы для "глубокого байндинга"  и делегированных событий.

```js
app = new Matreshka;
app.int = {int: '123'};
app.bindNode( 'int.int', '.int' );
// свяжет int в объекте int с элементом
```

Но проблема ясна, нужно подумать, как экранировать такие символы.

Спасибо за репорт.

**Comment by finom** [comment]
@undermuz решения пока что нет. Если это возможно, уберите точки из имени свойства.

**Comment by finom** [comment]
Единственный вариант, который есть - это "экранировать" точку двойным слешем:
```js
app.bindNode( 'int\\.int', '.int' );
```

**Comment by finom** [comment]
@undermuz добавлен менее злой костыль в виде свойства ``deep: false`` для 4-го аргумента bindNode.

http://jsfiddle.net/8d5o157b/2/

**Comment by undermuz** [comment]
@finom спасибо :)

**Comment by finom** [comment]
@undermuz можно пока что использовать версию из бранча develop.
