### ISSUE TITLE
Не срабатывают события по изменению вложенных в объект свойств

### ISSUE THREAD

**Issue by atnartur** [matreshkajs/matreshka#29]
Здравствуйте! Не срабатывают события по изменению вложенных в объект свойств.

```javascript
class EditModal extends MK.Object{
	constructor(data) {
		super();
		this.jset({
			data: {
				group_id: ''
			}
		});;

		this.bindNode({
			'data.group_id': ':sandbox select[name=group_id]'
		}, {
			setValue: (v) => {
				$(this).val(v);
			}
		});

		var self = this;

		this.on('change:data.group_id', function(){
			console.log(111)
		});
	}
}
```

Есть `data.group_id`. Поле привязано к тегу `<select>`. По изменению `<select>` в консоль должен попадать определенный текст, но этого не происходит. 

[Повторил на Codepen](http://codepen.io/anon/pen/mPOKPQ?editors=1010)

**Comment by zveroboy** [comment]
@atnartur, посмотрите на [Хабре](https://habrahabr.ru/company/matreshka/blog/267513/) Пример 7.
Для Вашего случая правильным будет следующий вариант:

`this.on('data@change:group_id', function(){
            console.log(111);
        });`

[Codepen](http://codepen.io/anon/pen/VapYqp)

**Comment by finom** [comment]
@atnartur ``change:data.group_id`` будет слушать изменения в свойстве ``this["data.group_id"]``. @zveroboy прав.
