### ISSUE TITLE
addDataKeys('address_id date_time comment') is not a function

### ISSUE THREAD

**Issue by pimshtein** [matreshkajs/matreshka#31]
Такая ошибка возникает на старых браузерах, использующих движок webkit, например, opera < 31 версия.

**Comment by atnartur** [comment]
Чаще всего просят предоставить ссылку на какой-нибудь codepen.io для того, чтобы нагляднее видеть и понимать проблему. Не могли бы Вы изобразить случай на подобном сервисе?

**Comment by pimshtein** [comment]
Вот ссылка:
https://gist.github.com/anonymous/9f31237980b2ee9a4dde23641076e47e
Повторюсь: не работает на opera < 31 версии. Можете проверить.
Поставил версию 1.5.2 - там подобной ошибки нет.

**Comment by atnartur** [comment]
В Вашем примере не было подключено библиотек jQuery и Матрешки, которые используются в скрипте. Также не было инициализации объекта Матрешки. Поправил:
https://codepen.io/anon/pen/XdBzdj?editors=0010

**Comment by atnartur** [comment]
Открыл в 30 версии Оперы. Подключена последняя версия Матрешки. Бага нет. Раз исправлено в новой версии, может и нет смысла больше в этом issue?

**Comment by finom** [comment]
@pimshtein открыл в старой Опере (на Browserstack) пример, который сделал @atnartur, проблемы не увидел.

P. S. Багрепорты по старым версиям не принимаются :)
