### ISSUE TITLE
Возможность указывать индексы через квадратные скобки в третьем аргументе linkProps

### ISSUE THREAD

**Issue by Olegych92** [matreshkajs/matreshka#36]
Сейчас можно так
```
var object = {
  a: [1],
  b: [2]
};

MK.linkProps(object, 'sum', 'a.0 b.0', function (a0, b0) {
  return a0+b0;
});
```

Хотелось бы более привычный и интуитивно понятный синтаксис для указания индекса `'a[0] b[0]'` и так можно было бы указывать невалидные ключи, например с точкой `'a["key.with.dots"]'`, что сейчас видимо не получится сделать

**Comment by finom** [comment]
Если можно, опишите эту issue  на английском языке. С выходом второй версии будет запрещено писать сюда на языке отличном от английского, а русскоязычные репорты и реквесты будут переведены в репку в моём личном аккаунте.

**Comment by finom** [comment]
Я долго думал об этой возможности и пришел к выводу, что этот синтаксис усложнит и без того сложный набор вариаций метода. Во второй версии будет флаг ``exactKey``, который говорит о том, что переданная строка - это не путь к свойству а само имя свойства. 

Закрываю ишью, так как она касается нового синтаксиса, а не нового флага или проблемы в целом. Спасибо за активность.
