### ISSUE TITLE
where is the doc in version 2.0?

### ISSUE THREAD

**Issue by rupertqin** [matreshkajs/matreshka#45]

**Comment by finom** [comment]
matreshka.io :)

I guess you've got cache issues. Make Ctrl + Enter.

**Comment by rupertqin** [comment]
I see there is small text "v1.8.0",  so it actully is v2.0?

**Comment by finom** [comment]
As I said above this is the cache issue. You need to clear cache somehow to see 2.1.0. I have the same issue on my mobile phone.
